routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /membership/: members/membership
  /.well-known/acme-challenge/jGqTv7BRrNlGYMPKBjKg794g5zBhPIHjcI6E7fpv2T4/: ../london/index

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
